version: '3.9'
services:
  wordpress:
    image: wordpress:6.0-php7.4-apache
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: plugin
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress-news-to-sender-net:/var/www/html/wp-content/plugins/wordpress-news-to-sender-net
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: plugin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
