name: Deploy to WordPress.org
on:
  push:
#    tags:
#      - "*"

jobs:
  deploy:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
          dry-run: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: posts-to-sender-net
          SOURCE_DIR: plugin
          VERSION: 0.0.1-beta

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{github.workspace}}/${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}