name: Deploy to WordPress.org

on:
  release:
    types: [released]

jobs:
  deploy:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: posts-to-sender-net
          BUILD_DIR: plugin/